/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Quiz } from "./Quiz";
import { QuizCountArgs } from "./QuizCountArgs";
import { QuizFindManyArgs } from "./QuizFindManyArgs";
import { QuizFindUniqueArgs } from "./QuizFindUniqueArgs";
import { CreateQuizArgs } from "./CreateQuizArgs";
import { UpdateQuizArgs } from "./UpdateQuizArgs";
import { DeleteQuizArgs } from "./DeleteQuizArgs";
import { ResultFindManyArgs } from "../../result/base/ResultFindManyArgs";
import { Result } from "../../result/base/Result";
import { QuizCreateInput } from "./QuizCreateInput";
import { QuizService } from "../quiz.service";
@graphql.Resolver(() => Quiz)
export class QuizResolverBase {
  constructor(protected readonly service: QuizService) {}

  async _quizzesMeta(
    @graphql.Args() args: QuizCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Quiz])
  async quizzes(@graphql.Args() args: QuizFindManyArgs): Promise<Quiz[]> {
    return this.service.quizzes(args);
  }

  @graphql.Query(() => Quiz, { nullable: true })
  async quiz(@graphql.Args() args: QuizFindUniqueArgs): Promise<Quiz | null> {
    const result = await this.service.quiz(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Quiz)
  async createQuiz(@graphql.Args() args: CreateQuizArgs): Promise<Quiz> {
    return await this.service.createQuiz({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Quiz)
  async updateQuiz(@graphql.Args() args: UpdateQuizArgs): Promise<Quiz | null> {
    try {
      return await this.service.updateQuiz({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Quiz)
  async deleteQuiz(@graphql.Args() args: DeleteQuizArgs): Promise<Quiz | null> {
    try {
      return await this.service.deleteQuiz(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Result], { name: "results" })
  async findResults(
    @graphql.Parent() parent: Quiz,
    @graphql.Args() args: ResultFindManyArgs
  ): Promise<Result[]> {
    const results = await this.service.findResults(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.Mutation(() => Quiz)
  async CreateQuiz(
    @graphql.Args()
    args: QuizCreateInput
  ): Promise<Quiz> {
    return this.service.CreateQuiz(args);
  }
}
